fix: update tealdeer version (#4)
Use pre-built 1.8.1 since it is not available
on github action's ubuntu version.

Use XDG_DATA_HOME for tealdeer as they
changed their env policy

diff --git a/scripts/run_benchmarks b/scripts/run_benchmarks
--- a/scripts/run_benchmarks
+++ b/scripts/run_benchmarks
@@ -12,6 +12,8 @@
 #
 #  - $1 => Command to clear OS file system caches.
 
+set -e
+
 CLEAR_CACHE_CMD="$1"
 
 shift || {
@@ -29,6 +31,8 @@ while IFS=, read env cmd; do
 	cache_path="$PWD/caches/$cmd"
 	mkdir -p "$cache_path"
 	bash -c "$CLEAR_CACHE_CMD"
+	# NOTE: this next command might silently fail due to intrication of
+	# `bash -c`, `time` and piping to `awk`.
 	timing_s=$({ time bash -c "$env=\"$cache_path\" ./$cmd --update"; } 2>&1 | awk '/real/ {print $2}')
 	echo "Updated cache for $cmd in $timing_s."
 	echo "$cmd,$timing_s" >>update_times.csv
